### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by sathickibrahims18** [werowe/MLexamples#1]
Hi Werowe,

When I ran the model fit in logisticRegression.ipynb, I got an error 
 **Failed Reason: InternalServerError: We encountered an internal error. Please try again.**

Could you please help me to solve this issue

Thanks,
Sathick Ibrahim

**Comment by werowe** [comment]
That has nothing to do with code.  You have an error with whatever server
in running on the backend, eg spark

**Comment by sathickibrahims18** [comment]
Thanks Werowe, It's working.
